### ISSUE TITLE
Example project doesn't build

### ISSUE THREAD

**Issue by sveinungkb** [mparticle-integrations/mparticle-android-integration-example#1]
The kit example seems to need a project property `version` to compile or else the plugin will add a dependency to `compile 'com.mparticle:android-kit-base:unspecified'` which naturally doesn't resolve.

https://github.com/mParticle/mparticle-android-sdk/blob/master/kit-plugin/src/main/groovy/com/mparticle/kits/KitPlugin.groovy#L19

Working build.gradle:
```
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath 'com.mparticle:android-kit-plugin:+'
    }
}

project.version = '4.5.4'

apply plugin: 'com.mparticle.kit'
```

**Comment by samdozor** [comment]
hey @sveinungkb thanks for pointing this out. These are usually built as submodules of the core sdk, which sets the version. For now go ahead and manually set the version as you've done. But, I'll keep this issue open until there's a more generic resolution.

**Comment by sveinungkb** [comment]
Ah, understand! 
Yeah, I just cloned the example and noticed it didn't build. Thanks for the quick response!
